services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: malak
      POSTGRES_PASSWORD: malak
      POSTGRES_DB: malak
    ports:
      - "9432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb

  redis:
    image: redis
    ports:
      - "9379:6379"

  otel:
    image: grafana/otel-lgtm
    ports:
      - "9317:4317"
      - "9318:4318"
      - "9300:3000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker-data/minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
  postgres_data:
    driver: local
