services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: malak
      POSTGRES_PASSWORD: malak
      POSTGRES_DB: malak
    ports:
      - "9432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb

  redis:
    image: redis
    ports:
      - "9379:6379"

  otel:
    image: grafana/otel-lgtm
    ports:
      - "9317:4317"
      - "9318:4318"
      - "9300:3000"

volumes:
  postgres_data:
    driver: local
