// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package malak

import (
	"errors"
	"fmt"
)

const (
	// FundraisePipelineColumnTypeNormal is a FundraisePipelineColumnType of type Normal.
	FundraisePipelineColumnTypeNormal FundraisePipelineColumnType = iota
	// FundraisePipelineColumnTypeClosed is a FundraisePipelineColumnType of type Closed.
	FundraisePipelineColumnTypeClosed
)

var ErrInvalidFundraisePipelineColumnType = errors.New("not a valid FundraisePipelineColumnType")

const _FundraisePipelineColumnTypeName = "normalclosed"

var _FundraisePipelineColumnTypeMap = map[FundraisePipelineColumnType]string{
	FundraisePipelineColumnTypeNormal: _FundraisePipelineColumnTypeName[0:6],
	FundraisePipelineColumnTypeClosed: _FundraisePipelineColumnTypeName[6:12],
}

// String implements the Stringer interface.
func (x FundraisePipelineColumnType) String() string {
	if str, ok := _FundraisePipelineColumnTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("FundraisePipelineColumnType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FundraisePipelineColumnType) IsValid() bool {
	_, ok := _FundraisePipelineColumnTypeMap[x]
	return ok
}

var _FundraisePipelineColumnTypeValue = map[string]FundraisePipelineColumnType{
	_FundraisePipelineColumnTypeName[0:6]:  FundraisePipelineColumnTypeNormal,
	_FundraisePipelineColumnTypeName[6:12]: FundraisePipelineColumnTypeClosed,
}

// ParseFundraisePipelineColumnType attempts to convert a string to a FundraisePipelineColumnType.
func ParseFundraisePipelineColumnType(name string) (FundraisePipelineColumnType, error) {
	if x, ok := _FundraisePipelineColumnTypeValue[name]; ok {
		return x, nil
	}
	return FundraisePipelineColumnType(0), fmt.Errorf("%s is %w", name, ErrInvalidFundraisePipelineColumnType)
}

const (
	// FundraisePipelineStageFamilyAndFriend is a FundraisePipelineStage of type family_and_friend.
	FundraisePipelineStageFamilyAndFriend FundraisePipelineStage = "family_and_friend"
	// FundraisePipelineStagePreSeed is a FundraisePipelineStage of type pre_seed.
	FundraisePipelineStagePreSeed FundraisePipelineStage = "pre_seed"
	// FundraisePipelineStageSeed is a FundraisePipelineStage of type seed.
	FundraisePipelineStageSeed FundraisePipelineStage = "seed"
	// FundraisePipelineStageSeriesA is a FundraisePipelineStage of type series_a.
	FundraisePipelineStageSeriesA FundraisePipelineStage = "series_a"
	// FundraisePipelineStageSeriesB is a FundraisePipelineStage of type series_b.
	FundraisePipelineStageSeriesB FundraisePipelineStage = "series_b"
	// FundraisePipelineStageSeriesC is a FundraisePipelineStage of type series_c.
	FundraisePipelineStageSeriesC FundraisePipelineStage = "series_c"
)

var ErrInvalidFundraisePipelineStage = errors.New("not a valid FundraisePipelineStage")

// String implements the Stringer interface.
func (x FundraisePipelineStage) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FundraisePipelineStage) IsValid() bool {
	_, err := ParseFundraisePipelineStage(string(x))
	return err == nil
}

var _FundraisePipelineStageValue = map[string]FundraisePipelineStage{
	"family_and_friend": FundraisePipelineStageFamilyAndFriend,
	"pre_seed":          FundraisePipelineStagePreSeed,
	"seed":              FundraisePipelineStageSeed,
	"series_a":          FundraisePipelineStageSeriesA,
	"series_b":          FundraisePipelineStageSeriesB,
	"series_c":          FundraisePipelineStageSeriesC,
}

// ParseFundraisePipelineStage attempts to convert a string to a FundraisePipelineStage.
func ParseFundraisePipelineStage(name string) (FundraisePipelineStage, error) {
	if x, ok := _FundraisePipelineStageValue[name]; ok {
		return x, nil
	}
	return FundraisePipelineStage(""), fmt.Errorf("%s is %w", name, ErrInvalidFundraisePipelineStage)
}
