// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package malak

import (
	"errors"
	"fmt"
)

const (
	// IntegrationChartFrequencyTypeDaily is a IntegrationChartFrequencyType of type Daily.
	IntegrationChartFrequencyTypeDaily IntegrationChartFrequencyType = iota
	// IntegrationChartFrequencyTypeMonthly is a IntegrationChartFrequencyType of type Monthly.
	IntegrationChartFrequencyTypeMonthly
)

var ErrInvalidIntegrationChartFrequencyType = errors.New("not a valid IntegrationChartFrequencyType")

const _IntegrationChartFrequencyTypeName = "dailymonthly"

var _IntegrationChartFrequencyTypeMap = map[IntegrationChartFrequencyType]string{
	IntegrationChartFrequencyTypeDaily:   _IntegrationChartFrequencyTypeName[0:5],
	IntegrationChartFrequencyTypeMonthly: _IntegrationChartFrequencyTypeName[5:12],
}

// String implements the Stringer interface.
func (x IntegrationChartFrequencyType) String() string {
	if str, ok := _IntegrationChartFrequencyTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("IntegrationChartFrequencyType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationChartFrequencyType) IsValid() bool {
	_, ok := _IntegrationChartFrequencyTypeMap[x]
	return ok
}

var _IntegrationChartFrequencyTypeValue = map[string]IntegrationChartFrequencyType{
	_IntegrationChartFrequencyTypeName[0:5]:  IntegrationChartFrequencyTypeDaily,
	_IntegrationChartFrequencyTypeName[5:12]: IntegrationChartFrequencyTypeMonthly,
}

// ParseIntegrationChartFrequencyType attempts to convert a string to a IntegrationChartFrequencyType.
func ParseIntegrationChartFrequencyType(name string) (IntegrationChartFrequencyType, error) {
	if x, ok := _IntegrationChartFrequencyTypeValue[name]; ok {
		return x, nil
	}
	return IntegrationChartFrequencyType(0), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationChartFrequencyType)
}

const (
	// IntegrationChartInternalNameTypeMercuryAccount is a IntegrationChartInternalNameType of type mercury_account.
	IntegrationChartInternalNameTypeMercuryAccount IntegrationChartInternalNameType = "mercury_account"
	// IntegrationChartInternalNameTypeMercuryAccountTransaction is a IntegrationChartInternalNameType of type mercury_account_transaction.
	IntegrationChartInternalNameTypeMercuryAccountTransaction IntegrationChartInternalNameType = "mercury_account_transaction"
	// IntegrationChartInternalNameTypeBrexAccount is a IntegrationChartInternalNameType of type brex_account.
	IntegrationChartInternalNameTypeBrexAccount IntegrationChartInternalNameType = "brex_account"
	// IntegrationChartInternalNameTypeBrexAccountTransaction is a IntegrationChartInternalNameType of type brex_account_transaction.
	IntegrationChartInternalNameTypeBrexAccountTransaction IntegrationChartInternalNameType = "brex_account_transaction"
)

var ErrInvalidIntegrationChartInternalNameType = errors.New("not a valid IntegrationChartInternalNameType")

// String implements the Stringer interface.
func (x IntegrationChartInternalNameType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationChartInternalNameType) IsValid() bool {
	_, err := ParseIntegrationChartInternalNameType(string(x))
	return err == nil
}

var _IntegrationChartInternalNameTypeValue = map[string]IntegrationChartInternalNameType{
	"mercury_account":             IntegrationChartInternalNameTypeMercuryAccount,
	"mercury_account_transaction": IntegrationChartInternalNameTypeMercuryAccountTransaction,
	"brex_account":                IntegrationChartInternalNameTypeBrexAccount,
	"brex_account_transaction":    IntegrationChartInternalNameTypeBrexAccountTransaction,
}

// ParseIntegrationChartInternalNameType attempts to convert a string to a IntegrationChartInternalNameType.
func ParseIntegrationChartInternalNameType(name string) (IntegrationChartInternalNameType, error) {
	if x, ok := _IntegrationChartInternalNameTypeValue[name]; ok {
		return x, nil
	}
	return IntegrationChartInternalNameType(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationChartInternalNameType)
}

const (
	// IntegrationChartTypeBar is a IntegrationChartType of type bar.
	IntegrationChartTypeBar IntegrationChartType = "bar"
	// IntegrationChartTypePie is a IntegrationChartType of type pie.
	IntegrationChartTypePie IntegrationChartType = "pie"
)

var ErrInvalidIntegrationChartType = errors.New("not a valid IntegrationChartType")

// String implements the Stringer interface.
func (x IntegrationChartType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationChartType) IsValid() bool {
	_, err := ParseIntegrationChartType(string(x))
	return err == nil
}

var _IntegrationChartTypeValue = map[string]IntegrationChartType{
	"bar": IntegrationChartTypeBar,
	"pie": IntegrationChartTypePie,
}

// ParseIntegrationChartType attempts to convert a string to a IntegrationChartType.
func ParseIntegrationChartType(name string) (IntegrationChartType, error) {
	if x, ok := _IntegrationChartTypeValue[name]; ok {
		return x, nil
	}
	return IntegrationChartType(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationChartType)
}

const (
	// IntegrationDataPointTypeCurrency is a IntegrationDataPointType of type currency.
	IntegrationDataPointTypeCurrency IntegrationDataPointType = "currency"
	// IntegrationDataPointTypeOthers is a IntegrationDataPointType of type others.
	IntegrationDataPointTypeOthers IntegrationDataPointType = "others"
)

var ErrInvalidIntegrationDataPointType = errors.New("not a valid IntegrationDataPointType")

// String implements the Stringer interface.
func (x IntegrationDataPointType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationDataPointType) IsValid() bool {
	_, err := ParseIntegrationDataPointType(string(x))
	return err == nil
}

var _IntegrationDataPointTypeValue = map[string]IntegrationDataPointType{
	"currency": IntegrationDataPointTypeCurrency,
	"others":   IntegrationDataPointTypeOthers,
}

// ParseIntegrationDataPointType attempts to convert a string to a IntegrationDataPointType.
func ParseIntegrationDataPointType(name string) (IntegrationDataPointType, error) {
	if x, ok := _IntegrationDataPointTypeValue[name]; ok {
		return x, nil
	}
	return IntegrationDataPointType(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationDataPointType)
}

const (
	// IntegrationProviderStripe is a IntegrationProvider of type stripe.
	IntegrationProviderStripe IntegrationProvider = "stripe"
	// IntegrationProviderPaystack is a IntegrationProvider of type paystack.
	IntegrationProviderPaystack IntegrationProvider = "paystack"
	// IntegrationProviderFlutterwave is a IntegrationProvider of type flutterwave.
	IntegrationProviderFlutterwave IntegrationProvider = "flutterwave"
	// IntegrationProviderMercury is a IntegrationProvider of type mercury.
	IntegrationProviderMercury IntegrationProvider = "mercury"
	// IntegrationProviderBrex is a IntegrationProvider of type brex.
	IntegrationProviderBrex IntegrationProvider = "brex"
)

var ErrInvalidIntegrationProvider = errors.New("not a valid IntegrationProvider")

// String implements the Stringer interface.
func (x IntegrationProvider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationProvider) IsValid() bool {
	_, err := ParseIntegrationProvider(string(x))
	return err == nil
}

var _IntegrationProviderValue = map[string]IntegrationProvider{
	"stripe":      IntegrationProviderStripe,
	"paystack":    IntegrationProviderPaystack,
	"flutterwave": IntegrationProviderFlutterwave,
	"mercury":     IntegrationProviderMercury,
	"brex":        IntegrationProviderBrex,
}

// ParseIntegrationProvider attempts to convert a string to a IntegrationProvider.
func ParseIntegrationProvider(name string) (IntegrationProvider, error) {
	if x, ok := _IntegrationProviderValue[name]; ok {
		return x, nil
	}
	return IntegrationProvider(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationProvider)
}

const (
	// IntegrationTypeOauth2 is a IntegrationType of type oauth2.
	IntegrationTypeOauth2 IntegrationType = "oauth2"
	// IntegrationTypeApiKey is a IntegrationType of type api_key.
	IntegrationTypeApiKey IntegrationType = "api_key"
)

var ErrInvalidIntegrationType = errors.New("not a valid IntegrationType")

// String implements the Stringer interface.
func (x IntegrationType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IntegrationType) IsValid() bool {
	_, err := ParseIntegrationType(string(x))
	return err == nil
}

var _IntegrationTypeValue = map[string]IntegrationType{
	"oauth2":  IntegrationTypeOauth2,
	"api_key": IntegrationTypeApiKey,
}

// ParseIntegrationType attempts to convert a string to a IntegrationType.
func ParseIntegrationType(name string) (IntegrationType, error) {
	if x, ok := _IntegrationTypeValue[name]; ok {
		return x, nil
	}
	return IntegrationType(""), fmt.Errorf("%s is %w", name, ErrInvalidIntegrationType)
}
