// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package malak

import (
	"errors"
	"fmt"
)

const (
	// ContactShareItemTypeUpdate is a ContactShareItemType of type update.
	ContactShareItemTypeUpdate ContactShareItemType = "update"
	// ContactShareItemTypeDashboard is a ContactShareItemType of type dashboard.
	ContactShareItemTypeDashboard ContactShareItemType = "dashboard"
	// ContactShareItemTypeDeck is a ContactShareItemType of type deck.
	ContactShareItemTypeDeck ContactShareItemType = "deck"
)

var ErrInvalidContactShareItemType = errors.New("not a valid ContactShareItemType")

// String implements the Stringer interface.
func (x ContactShareItemType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ContactShareItemType) IsValid() bool {
	_, err := ParseContactShareItemType(string(x))
	return err == nil
}

var _ContactShareItemTypeValue = map[string]ContactShareItemType{
	"update":    ContactShareItemTypeUpdate,
	"dashboard": ContactShareItemTypeDashboard,
	"deck":      ContactShareItemTypeDeck,
}

// ParseContactShareItemType attempts to convert a string to a ContactShareItemType.
func ParseContactShareItemType(name string) (ContactShareItemType, error) {
	if x, ok := _ContactShareItemTypeValue[name]; ok {
		return x, nil
	}
	return ContactShareItemType(""), fmt.Errorf("%s is %w", name, ErrInvalidContactShareItemType)
}
