// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package malak

import (
	"errors"
	"fmt"
)

const (
	// SystemTemplateFilterMostUsed is a SystemTemplateFilter of type most_used.
	SystemTemplateFilterMostUsed SystemTemplateFilter = "most_used"
	// SystemTemplateFilterRecentlyCreated is a SystemTemplateFilter of type recently_created.
	SystemTemplateFilterRecentlyCreated SystemTemplateFilter = "recently_created"
	// SystemTemplateFilterAll is a SystemTemplateFilter of type all.
	SystemTemplateFilterAll SystemTemplateFilter = "all"
)

var ErrInvalidSystemTemplateFilter = errors.New("not a valid SystemTemplateFilter")

// String implements the Stringer interface.
func (x SystemTemplateFilter) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SystemTemplateFilter) IsValid() bool {
	_, err := ParseSystemTemplateFilter(string(x))
	return err == nil
}

var _SystemTemplateFilterValue = map[string]SystemTemplateFilter{
	"most_used":        SystemTemplateFilterMostUsed,
	"recently_created": SystemTemplateFilterRecentlyCreated,
	"all":              SystemTemplateFilterAll,
}

// ParseSystemTemplateFilter attempts to convert a string to a SystemTemplateFilter.
func ParseSystemTemplateFilter(name string) (SystemTemplateFilter, error) {
	if x, ok := _SystemTemplateFilterValue[name]; ok {
		return x, nil
	}
	return SystemTemplateFilter(""), fmt.Errorf("%s is %w", name, ErrInvalidSystemTemplateFilter)
}
