// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package malak

import (
	"errors"
	"fmt"
)

const (
	// UpdateStatusDraft is a UpdateStatus of type draft.
	UpdateStatusDraft UpdateStatus = "draft"
	// UpdateStatusSent is a UpdateStatus of type sent.
	UpdateStatusSent UpdateStatus = "sent"
)

var ErrInvalidUpdateStatus = errors.New("not a valid UpdateStatus")

// String implements the Stringer interface.
func (x UpdateStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UpdateStatus) IsValid() bool {
	_, err := ParseUpdateStatus(string(x))
	return err == nil
}

var _UpdateStatusValue = map[string]UpdateStatus{
	"draft": UpdateStatusDraft,
	"sent":  UpdateStatusSent,
}

// ParseUpdateStatus attempts to convert a string to a UpdateStatus.
func ParseUpdateStatus(name string) (UpdateStatus, error) {
	if x, ok := _UpdateStatusValue[name]; ok {
		return x, nil
	}
	return UpdateStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidUpdateStatus)
}
