receivers:
prometheus:
  config:
    scrape_configs:
      - job_name: "bundler"
        scrape_interval: 10s
        static_configs:
          - targets: ["host.docker.internal:4337"]
        basic_auth:
          username: malak
          password: malak

processors:
batch:

exporters:
otlp:
  endpoint: "otel:4317"
  tls:
    insecure: true

service:
pipelines:
  metrics:
    receivers: [prometheus]
    processors: [batch]
    exporters: [otlp]
