// Code generated by MockGen. DO NOT EDIT.
// Source: fundraising.go
//
// Generated by this command:
//
//	mockgen -source=fundraising.go -destination=mocks/fundraising.go -package=malak_mocks
//

// Package malak_mocks is a generated GoMock package.
package malak_mocks

import (
	context "context"
	reflect "reflect"

	malak "github.com/ayinke-llc/malak"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFundraisingPipelineRepository is a mock of FundraisingPipelineRepository interface.
type MockFundraisingPipelineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFundraisingPipelineRepositoryMockRecorder
	isgomock struct{}
}

// MockFundraisingPipelineRepositoryMockRecorder is the mock recorder for MockFundraisingPipelineRepository.
type MockFundraisingPipelineRepositoryMockRecorder struct {
	mock *MockFundraisingPipelineRepository
}

// NewMockFundraisingPipelineRepository creates a new mock instance.
func NewMockFundraisingPipelineRepository(ctrl *gomock.Controller) *MockFundraisingPipelineRepository {
	mock := &MockFundraisingPipelineRepository{ctrl: ctrl}
	mock.recorder = &MockFundraisingPipelineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundraisingPipelineRepository) EXPECT() *MockFundraisingPipelineRepositoryMockRecorder {
	return m.recorder
}

// AddContactToBoard mocks base method.
func (m *MockFundraisingPipelineRepository) AddContactToBoard(arg0 context.Context, arg1 *malak.AddContactToBoardOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContactToBoard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContactToBoard indicates an expected call of AddContactToBoard.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) AddContactToBoard(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContactToBoard", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).AddContactToBoard), arg0, arg1)
}

// Board mocks base method.
func (m *MockFundraisingPipelineRepository) Board(arg0 context.Context, arg1 *malak.FundraisingPipeline) ([]malak.FundraisingPipelineColumn, []malak.FundraiseContact, []malak.FundraiseContactPosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Board", arg0, arg1)
	ret0, _ := ret[0].([]malak.FundraisingPipelineColumn)
	ret1, _ := ret[1].([]malak.FundraiseContact)
	ret2, _ := ret[2].([]malak.FundraiseContactPosition)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Board indicates an expected call of Board.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) Board(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Board", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).Board), arg0, arg1)
}

// CloseBoard mocks base method.
func (m *MockFundraisingPipelineRepository) CloseBoard(arg0 context.Context, arg1 *malak.FundraisingPipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseBoard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseBoard indicates an expected call of CloseBoard.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) CloseBoard(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseBoard", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).CloseBoard), arg0, arg1)
}

// Create mocks base method.
func (m *MockFundraisingPipelineRepository) Create(arg0 context.Context, arg1 *malak.FundraisingPipeline, arg2 ...malak.FundraisingPipelineColumn) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) Create(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).Create), varargs...)
}

// DefaultColumn mocks base method.
func (m *MockFundraisingPipelineRepository) DefaultColumn(arg0 context.Context, arg1 *malak.FundraisingPipeline) (malak.FundraisingPipelineColumn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultColumn", arg0, arg1)
	ret0, _ := ret[0].(malak.FundraisingPipelineColumn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DefaultColumn indicates an expected call of DefaultColumn.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) DefaultColumn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultColumn", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).DefaultColumn), arg0, arg1)
}

// Get mocks base method.
func (m *MockFundraisingPipelineRepository) Get(arg0 context.Context, arg1 malak.FetchPipelineOptions) (*malak.FundraisingPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*malak.FundraisingPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).Get), arg0, arg1)
}

// GetContact mocks base method.
func (m *MockFundraisingPipelineRepository) GetContact(arg0 context.Context, arg1, arg2 uuid.UUID) (*malak.FundraiseContact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContact", arg0, arg1, arg2)
	ret0, _ := ret[0].(*malak.FundraiseContact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContact indicates an expected call of GetContact.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) GetContact(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContact", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).GetContact), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockFundraisingPipelineRepository) List(arg0 context.Context, arg1 malak.ListPipelineOptions) ([]malak.FundraisingPipeline, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]malak.FundraisingPipeline)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).List), arg0, arg1)
}

// UpdateBoardContact mocks base method.
func (m *MockFundraisingPipelineRepository) UpdateBoardContact(arg0 context.Context, arg1 *malak.FundraiseContactDealDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBoardContact", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBoardContact indicates an expected call of UpdateBoardContact.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) UpdateBoardContact(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBoardContact", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).UpdateBoardContact), arg0, arg1)
}

// UpdateContactDeal mocks base method.
func (m *MockFundraisingPipelineRepository) UpdateContactDeal(arg0 context.Context, arg1 *malak.FundraisingPipeline, arg2 malak.UpdateContactDealOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContactDeal", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContactDeal indicates an expected call of UpdateContactDeal.
func (mr *MockFundraisingPipelineRepositoryMockRecorder) UpdateContactDeal(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContactDeal", reflect.TypeOf((*MockFundraisingPipelineRepository)(nil).UpdateContactDeal), arg0, arg1, arg2)
}
