// Code generated by MockGen. DO NOT EDIT.
// Source: integration.go
//
// Generated by this command:
//
//	mockgen -source=integration.go -destination=mocks/integration.go -package=malak_mocks
//

// Package malak_mocks is a generated GoMock package.
package malak_mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIntegrationRepository is a mock of IntegrationRepository interface.
type MockIntegrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationRepositoryMockRecorder
	isgomock struct{}
}

// MockIntegrationRepositoryMockRecorder is the mock recorder for MockIntegrationRepository.
type MockIntegrationRepositoryMockRecorder struct {
	mock *MockIntegrationRepository
}

// NewMockIntegrationRepository creates a new mock instance.
func NewMockIntegrationRepository(ctrl *gomock.Controller) *MockIntegrationRepository {
	mock := &MockIntegrationRepository{ctrl: ctrl}
	mock.recorder = &MockIntegrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrationRepository) EXPECT() *MockIntegrationRepositoryMockRecorder {
	return m.recorder
}
