// Code generated by MockGen. DO NOT EDIT.
// Source: share.go
//
// Generated by this command:
//
//	mockgen -source=share.go -destination=mocks/share.go -package=malak_mocks
//

// Package malak_mocks is a generated GoMock package.
package malak_mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockContactShareRepository is a mock of ContactShareRepository interface.
type MockContactShareRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactShareRepositoryMockRecorder
	isgomock struct{}
}

// MockContactShareRepositoryMockRecorder is the mock recorder for MockContactShareRepository.
type MockContactShareRepositoryMockRecorder struct {
	mock *MockContactShareRepository
}

// NewMockContactShareRepository creates a new mock instance.
func NewMockContactShareRepository(ctrl *gomock.Controller) *MockContactShareRepository {
	mock := &MockContactShareRepository{ctrl: ctrl}
	mock.recorder = &MockContactShareRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactShareRepository) EXPECT() *MockContactShareRepositoryMockRecorder {
	return m.recorder
}
