export const EVENT_LOGIN_BUTTON_CLICKED = 'EVENT_LOGIN_BUTTON_CLICKED' as const
export const EVENT_UPDATE_DUPLICATE = 'EVENT_UPDATE_DUPLICATE' as const
export const EVENT_UPDATE_DELETE = 'EVENT_UPDATE_DELETE' as const
export const EVENT_TOGGLE_PINNED_STATE = 'EVENT_TOGGLE_PINNED_STATE' as const
