const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
const MALAK_TERMS_CONDITION_LINK =
  process.env.NEXT_PUBLIC_MALAK_TERMS_CONDITION_LINK ||
  "https://ayinke.ventures/malak/terms";
const MALAK_PRIVACY_POLICY_LINK =
  process.env.NEXT_PUBLIC_MALAK_PRIVACY_POLICY_LINK ||
  "https://ayinke.ventures/malak/privacy";
const MALAK_APP_URL = process.env.NEXT_PUBLIC_APP_URL || "https://app.malak.vc"

const MALAK_SENTRY_ENABLED =
  process.env.NEXT_PUBLIC_SENTRY_DSN ? true : false;
const MALAK_SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN;
const DECKS_DOMAIN = process.env.NEXT_PUBLIC_DECKS_DOMAIN;
const SUPPORT_EMAIL = process.env.NEXT_PUBLIC_SUPPORT_EMAIL;

const API_URL = process.env.NEXT_PUBLIC_API_URL;

export {
  GOOGLE_CLIENT_ID,
  MALAK_TERMS_CONDITION_LINK,
  MALAK_PRIVACY_POLICY_LINK,
  MALAK_SENTRY_DSN,
  MALAK_SENTRY_ENABLED,
  DECKS_DOMAIN,
  SUPPORT_EMAIL,
  MALAK_APP_URL,
  API_URL,
};
