ALTER TABLE dashboards
  ADD COLUMN description TEXT NOT NULL,
  ADD COLUMN chart_count SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
