on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

name: Build container Image
jobs:
  image:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag
        id: set_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/v}
            echo "TAG=${TAG}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Authenticate
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: adelowo
          DOCKER_REGISTRY_URL: ghcr.io
          DOCKER_PASSWORD: ${{ github.token }}

      - name: Build latest image
        run: |
          docker build \
            --build-arg COMMIT=${GITHUB_SHA::8} \
            --build-arg VERSION=${{ env.TAG }} \
            -t ghcr.io/${GITHUB_REPOSITORY}:${{ env.TAG }} .

      - name: Push
        id: push
        uses: actions-hub/docker@master
        with:
          args: push ghcr.io/${GITHUB_REPOSITORY}:${{ env.TAG }}

      - name: Attest
        uses: actions/attest@v2
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          predicate-type: "https://in-toto.io/attestation/release/v0.1"
          predicate: '{"purl":"pkg:oci/..."}'
          push-to-registry: true
