on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

name: Build container Image
jobs:
  image:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag
        id: set_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Remove the leading 'v' from the tag name
            TAG=${GITHUB_REF#refs/tags/v}
            echo "TAG=${TAG}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Authenticate
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: adelowo
          DOCKER_REGISTRY_URL: ghcr.io
          DOCKER_PASSWORD: ${{ github.token }}

      - name: Build latest image
        run: |
          docker build \
            --build-arg COMMIT=${GITHUB_SHA::8} \
            --build-arg VERSION=${{ env.TAG }} \
            -t ghcr.io/${GITHUB_REPOSITORY}:${{ env.TAG }} .

      - name: Push
        uses: actions-hub/docker@master
        with:
          args: push ghcr.io/${GITHUB_REPOSITORY}:${{ env.TAG }}
