on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

name: Build container Image
jobs:
  image:
    runs-on: "ubuntu-latest"

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag
        id: set_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/v}
            echo "TAG=${TAG}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          build-args: COMMIT:${GITHUB_SHA::8} VERSION:${{ env.TAG }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Attest
        uses: actions/attest@v2
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          predicate-type: "https://in-toto.io/attestation/release/v0.1"
          predicate: '{"purl":"pkg:oci/..."}'
          push-to-registry: true
