name: Deploy to Linode

# Long term, this needs to be fixed
# because of backports. If we are running v1.4.4 that has commit xyz that fixes a bug
# backported to v1.0.9, we do not want to migrate the cloud version
# So makes sense to be more strict on what gets pushed and branch
# but for now this works
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
      - name: Build app
        run: go build -o malak cmd/*.go

      - name: SCP to Linode instance ( Binary )
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: "root"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "malak"
          target: "/root"

      - name: Restart Malak systemd service
        uses: appleboy/ssh-action@master
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: "root"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_path: deploy/linode.sh
          envs: INFISICAL_CLIENT_ID,INFISICAL_CLIENT_SECRET
