name: Send update emails Job

on:
  schedule:
    ## run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  send-email-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Updates emailing cronjob
        uses: appleboy/ssh-action@master
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          CRON_TYPE: updates
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: "root"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_path: deploy/cron.sh
          envs: INFISICAL_CLIENT_ID,INFISICAL_CLIENT_SECRET,CRON_TYPE
