name: Run API keys revocation job

on:
  schedule:
    - cron: "10 0 * * *"

jobs:
  delete-keys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run api keys cronjob
        uses: appleboy/ssh-action@master
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          CRON_TYPE: delete-keys
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: "root"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_path: deploy/cron.sh
          envs: INFISICAL_CLIENT_ID,INFISICAL_CLIENT_SECRET,CRON_TYPE
